### ISSUE TITLE
Unable to compile ACE with VBCC

### ISSUE THREAD

**Issue by ozzyOuzo** [AmigaPorts/ACE#109]
I know, that you are recommending GCC but i gave it a go with VBCC (which is currently installed on my system) 

so i've change my env VAR from :

driveLocation/VBCC

to

driveLocation/VBCC/targets\m68k-amigaos

Maybe using NDK version 13 is part of the problem ?

the error from 'make all' :

error 0 in line 9 of "exec\nodes.h": declaration expected
        included from file "D:\vbcc\ndk13\include_h/exec\memory.h":4
        included from file "D:\ACE\include/ace\managers\memory.h":13
        included from file "D:\ACE\src\ace\managers\\memory.c":5
aborting...
1 error found!

**Comment by tehKaiN** [comment]
That may be NDK13 fault, although I use the one bundled with Bebbo's GCC and it works just fine. Have you looked at that exec/nodes.h file? Perhaps there's a typo or something that can be easily fixed?

Still, it's going to be a tip of an iceberg of errors. I use anonymous unions here and there, and last time I checked they were not supported in VBCC.

Do you have any reason against using GCC? I do my main development on it since it produced better code for me during the course of development of my games. Perhaps you can just make our life easier by switching to GCC. ;)

**Comment by ozzyOuzo** [comment]
nope no reason at all, as far as VBCC was mentioned i've just tested it as is ^^
i will install cygwin + Bebbo's GCC

keep on the good work.

**Comment by tehKaiN** [comment]
since we depart from VBCC's supported stuff and delve more into modern C/C++ and CMake, I doubt building with it will be available anytime soon. I'll leave doc pages as they are, but add a note that this is only for old versions and/or future use if VBCC development speeds up by any chance.
