### ISSUE TITLE
Add support for virtual filesystem in monolithic file

### ISSUE THREAD

**Issue by tehKaiN** [AmigaPorts/ACE#50]
Moved from #25 since it's currently not that critical but will be for moving to ROM-based platforms or squeezing into floppy. It would be cool to have an ability to work on plain file structure of host OS or on virtual FS based on monolithic file.

- [x] Determine lightweight, portable, virtual FS for such mode
- [x] Implement virtual storage access functions 
- [x] Migrate ACE into using either disk-based files or virtual storage
- [x] Ability to disable virtual FS overhead with single define during compilation
- [x] Implement a tool to transform required file structure to monolithic bigfile

Before we introduce another custom file format, let's look at embedded systems for similar mature solutions. Perhaps SquashFS would do the job? Or is it too bloated?

**Comment by tehKaiN** [comment]
I've found [romfs specs](https://www.kernel.org/doc/Documentation/filesystems/romfs.txt). Kinda overkill though.

**Comment by tehKaiN** [comment]
Nintendo uses [ExeFS](https://www.3dbrew.org/wiki/ExeFS) on their handhelds. However, it's quite barebone and it doesn't support long file names and directories.

**Comment by tehKaiN** [comment]
[QFSGen](https://www.state-machine.com/qtools/qfsgen.html) generates files as byte arrays in C code in similar fashion to [incbin](https://github.com/graphitemaster/incbin) and its [shell/bat polyglot variant](https://github.com/Sophrinix/incbin). We could have such tools a bit customized and build read-only filesystem on that.

**Comment by tehKaiN** [comment]
https://hackaday.com/2019/01/24/cool-tools-a-little-filesystem-that-keeps-your-bits-on-lock/

**Comment by tehKaiN** [comment]
Also, I thought today of using TAR files since it's de facto standard for archiving lots of small files into one without compression. There are cons however:

- Headers use ASCII coding, sizes are additionally coded in octal - wtf?
- files are saved as multiples of 512 bytes

Also I've found today https://github.com/MarcoPon/SeqBox. Apart from being error resistant I know nothing about it, except it apparently won't work in intended manner on OFS floppy drives.

**Comment by SamuraiCrow** [comment]
TAR stands for Tape ARchiver.  It's mainly used to get better compression under single file archivers like GZip and BZ2.  If you can figure a way to index into it, it might work as intended.On Sep 26, 2019 1:53 PM, KaiN <notifications@github.com> wrote:Also, I thought today of using TAR files since it's de facto standard for archiving lots of small files into one without compression. There are cons however:
Headers use ASCII coding, sizes are additionally coded in octal - wtf?files are saved as multiples of 512 bytes
Also I've found today https://github.com/MarcoPon/SeqBox. Apart from being error resistant I know nothing about it, except it apparently won't work in intended manner on OFS floppy drives.

**Comment by tehKaiN** [comment]
yeah, and that's what I'm aiming at in this issue. To have single file holding whole filesystem with as little overhead as possible, hopefully to support writing too.

Quake games were using [zip](https://en.wikipedia.org/wiki/Zip_(file_format)#Design) files renamed to .pak. I have yet to see if this won't be a better choice, but I think this may be a bit of an overkill.
